// ============================================================================
// ACCURATE ICAP PATTERN DATABASE
// All 31 ICAP AC patterns (AC-0 through AC-31)
// ============================================================================

const PATTERNS = [
  // NUCLEAR PATTERNS
  {
    id: 'AC-0',
    name: 'Negative',
    category: 'nuclear',
    level: 'competent',
    tier: 1,
    description: 'No staining. Negative control.',
    keyFeature: 'Complete absence of fluorescent staining',
    antigens: 'None',
    clinicalAssociation: 'Negative control / healthy individuals',
    confusedWith: [],
    goblinNote: 'The empty glass — no antibodies here. Clean bill of health.',
    frequency: 'baseline',
    type: 'negative',
    images: ["/images/patterns/ac-0/1502462422-0.jpg", "/images/patterns/ac-0/1502462439-0.jpg", "/images/patterns/ac-0/1502462497-0.jpg", "/images/patterns/ac-0/1502718949-0.jpg", "/images/patterns/ac-0/1505097615-0.jpg"],
  },
  {
    id: 'AC-1',
    name: 'Nuclear Homogeneous',
    category: 'nuclear',
    level: 'competent',
    tier: 1,
    description: 'Uniform smooth staining of entire nucleus, enhanced rim during mitosis.',
    keyFeature: 'Even, continuous fluorescence throughout the nucleus',
    antigens: 'dsDNA, nucleosomes, histones',
    clinicalAssociation: 'SLE, drug-induced lupus',
    confusedWith: ['AC-2'],
    goblinNote: 'Gryf\'s fingerprints — anti-dsDNA antibodies are IgG class, and Gryf is the one who goes rogue in lupus. The homogeneous pattern is his calling card.',
    frequency: 'very common',
    type: 'homogeneous',
    images: ["/images/patterns/ac-1/1473302187-0.jpg", "/images/patterns/ac-1/1473306947-0.jpg", "/images/patterns/ac-1/1473346177-0.jpg", "/images/patterns/ac-1/1617151987-0.jpg", "/images/patterns/ac-1/1625699092-0.jpg"],
  },
  {
    id: 'AC-2',
    name: 'Nuclear Dense Fine Speckled (DFS70)',
    category: 'nuclear',
    level: 'competent',
    tier: 1,
    description: 'Dense heterogeneous speckles, variable size/brightness, lunar surface texture. Antigens are DFS70/LEDGFp75 (NOT histones). Often found in healthy individuals.',
    keyFeature: 'Heterogeneous speckles of varying brightness, lunar/cratered appearance',
    antigens: 'DFS70/LEDGFp75',
    clinicalAssociation: 'Frequently found in HEALTHY individuals — negatively associated with systemic autoimmune disease when isolated',
    confusedWith: ['AC-1', 'AC-30'],
    goblinNote: 'The great impostor — looks alarming but AC-2 alone actually means you\'re probably fine. It\'s anti-DFS70, not the goblins going rogue. Knowing this pattern saves patients from unnecessary panic.',
    frequency: 'common',
    type: 'denseSpeckled',
    images: ["/images/patterns/ac-2/1473302361-0.jpg", "/images/patterns/ac-2/1473302380-0.jpg", "/images/patterns/ac-2/1505097674-0.jpg", "/images/patterns/ac-2/1617152044-0.jpg", "/images/patterns/ac-2/1625699150-0.jpg"],
  },
  {
    id: 'AC-3',
    name: 'Centromere',
    category: 'nuclear',
    level: 'competent',
    tier: 1,
    description: 'Discrete dots (40-80 per nucleus), one per chromosome, align on metaphase plate.',
    keyFeature: '40-80 evenly spaced dots, typically in a linear/clustered arrangement',
    antigens: 'CENP-A, CENP-B',
    clinicalAssociation: 'Limited cutaneous systemic sclerosis, Raynaud\'s, primary biliary cholangitis',
    confusedWith: ['AC-6', 'AC-7'],
    goblinNote: 'When Betty the B cell makes anti-centromere antibodies, this is the pattern. Betty\'s mostly behaving here — this one\'s more scleroderma than lupus.',
    frequency: 'moderately common',
    type: 'centromere',
    images: ["/images/patterns/ac-3/1473302467-0.jpg", "/images/patterns/ac-3/1473302479-0.jpg", "/images/patterns/ac-3/1473302490-0.jpg", "/images/patterns/ac-3/1473346483-0.jpg", "/images/patterns/ac-3/1625699243-0.jpg"],
  },
  {
    id: 'AC-4',
    name: 'Nuclear Fine Speckled',
    category: 'nuclear',
    level: 'competent',
    tier: 2,
    description: 'Small even speckles throughout nuclei. Smaller and more regular than AC-5.',
    keyFeature: 'Fine, regularly distributed speckles of uniform size',
    antigens: 'SS-A/Ro (Ro52+Ro60), SS-B/La, Mi-2, TIF1\u03B3, Ku',
    clinicalAssociation: 'Sj\u00F6gren\'s syndrome, SLE, dermatomyositis',
    confusedWith: ['AC-2', 'AC-5'],
    goblinNote: 'The speckled squad — Gryf (IgG) is usually behind anti-Ro/La. When Merlin (IgM) joins the party, things get complicated.',
    frequency: 'very common',
    type: 'fineSpeckled',
    images: ["/images/patterns/ac-4/1473302555-1.jpg", "/images/patterns/ac-4/1505097718-0.jpg", "/images/patterns/ac-4/1520600378-0.jpg", "/images/patterns/ac-4/1536360230-0.jpeg", "/images/patterns/ac-4/1625699327-0.jpg"],
  },
  {
    id: 'AC-5',
    name: 'Nuclear Large/Coarse Speckled',
    category: 'nuclear',
    level: 'competent',
    tier: 2,
    description: 'Larger prominent speckles, widely spaced. Visibly larger than AC-4.',
    keyFeature: 'Larger, more prominent speckles with clear spacing between them',
    antigens: 'Sm, U1-RNP',
    clinicalAssociation: 'Mixed connective tissue disease (MCTD), SLE',
    confusedWith: ['AC-4', 'AC-6'],
    goblinNote: 'Only ~65% of labs can reliably tell AC-4 from AC-5 apart. The coarse speckles are Sm and U1-RNP territory.',
    frequency: 'common',
    type: 'coarseSpeckled',
    images: ["/images/patterns/ac-5/1473302619-0.jpg", "/images/patterns/ac-5/1473302619-1.jpg", "/images/patterns/ac-5/1505097854-0.jpg", "/images/patterns/ac-5/1617152146-0.jpg", "/images/patterns/ac-5/1625699513-0.jpg"],
  },
  {
    id: 'AC-6',
    name: 'Multiple Nuclear Dots',
    category: 'nuclear',
    level: 'expert',
    tier: 2,
    description: 'Multiple discrete dots (6-20+) throughout nucleus, random distribution.',
    keyFeature: '6-20+ discrete bright dots, random pattern',
    antigens: 'Sp100',
    clinicalAssociation: 'Primary biliary cholangitis (PBC)',
    confusedWith: ['AC-3', 'AC-7'],
    goblinNote: 'More dots than AC-7 but fewer and bigger than centromere. When the liver\'s complaining, sometimes this is what you see.',
    frequency: 'less common',
    type: 'multipleNuclearDots',
    images: ["/images/patterns/ac-6/1473302657-0.jpg", "/images/patterns/ac-6/1473302781-0.jpg", "/images/patterns/ac-6/1473302845-0.jpg", "/images/patterns/ac-6/1505098378-0.jpg", "/images/patterns/ac-6/1625699575-0.jpg"],
  },
  {
    id: 'AC-7',
    name: 'Few Nuclear Dots',
    category: 'nuclear',
    level: 'expert',
    tier: 2,
    description: '1-6 discrete bright dots per nucleus (Cajal bodies or PML bodies).',
    keyFeature: '1-6 bright discrete dots, very few per nucleus',
    antigens: 'p80-coilin (Cajal bodies), PML protein',
    clinicalAssociation: 'Primary biliary cholangitis, Sj\u00F6gren\'s, SLE',
    confusedWith: ['AC-3', 'AC-6'],
    goblinNote: 'Sometimes less is more. These are Cajal bodies or PML bodies — specific nuclear organelles lighting up.',
    frequency: 'rare',
    type: 'fewNuclearDots',
    images: ["/images/patterns/ac-7/1473303112-0.jpg", "/images/patterns/ac-7/1473303112-1.jpg", "/images/patterns/ac-7/1473303112-2.jpg", "/images/patterns/ac-7/1473307968-0.jpg", "/images/patterns/ac-7/1505098074-0.jpg"],
  },
  {
    id: 'AC-8',
    name: 'Nucleolar Homogeneous',
    category: 'nuclear',
    level: 'competent',
    tier: 2,
    description: 'Smooth uniform staining of nucleolus.',
    keyFeature: 'Bright, smooth, continuous staining of the nucleolar region',
    antigens: 'PM-Scl75, PM-Scl100, Th/To, B23/nucleophosmin',
    clinicalAssociation: 'Systemic sclerosis, polymyositis/dermatomyositis overlap',
    confusedWith: ['AC-9', 'AC-10'],
    goblinNote: 'The nucleolus is the ribosome factory. Smooth uniform glow means antibodies coating it evenly.',
    frequency: 'moderately common',
    type: 'nucleolarHomogeneous',
    images: ["/images/patterns/ac-8/1473303186-0.jpg", "/images/patterns/ac-8/1505097998-0.jpg", "/images/patterns/ac-8/1520600429-0.jpg", "/images/patterns/ac-8/1536360826-0.jpeg", "/images/patterns/ac-8/1625700030-0.jpg"],
  },
  {
    id: 'AC-9',
    name: 'Nucleolar Clumpy',
    category: 'nuclear',
    level: 'expert',
    tier: 3,
    description: 'Clumpy/coarse granular nucleolar staining. Requires 400x magnification to reliably distinguish from AC-8.',
    keyFeature: 'Coarse, granular, clumpy appearance in nucleolus (like cottage cheese vs cream)',
    antigens: 'U3-RNP (fibrillarin)',
    clinicalAssociation: 'Diffuse cutaneous systemic sclerosis',
    confusedWith: ['AC-8', 'AC-10'],
    goblinNote: 'Clumpy like cottage cheese instead of smooth cream. Anti-fibrillarin = diffuse scleroderma territory. Requires 400x to distinguish from AC-8.',
    frequency: 'less common',
    type: 'nucleolarClumpy',
    images: ["/images/patterns/ac-9/1473303223-0.jpg", "/images/patterns/ac-9/1473303288-0.jpg", "/images/patterns/ac-9/1473346653-0.jpg", "/images/patterns/ac-9/1536360747-0.jpeg", "/images/patterns/ac-9/processed_Ye4CGySyWGrnmPeXaXpVA4GqPVZU3m4LFjQFJMuJ.jpg"],
  },
  {
    id: 'AC-10',
    name: 'Nucleolar Punctate/Speckled',
    category: 'nuclear',
    level: 'expert',
    tier: 3,
    description: 'Fine speckled pattern within nucleolus only.',
    keyFeature: 'Fine speckles confined to the nucleolar region',
    antigens: 'RNA polymerase I, hUBF/NOR-90',
    clinicalAssociation: 'Systemic sclerosis, SLE',
    confusedWith: ['AC-8', 'AC-9'],
    goblinNote: 'The nucleolus is spotted — speckles confined to just the nucleolus, not the whole nucleus. Only about a third of lab professionals can reliably sub-type the nucleolar trio.',
    frequency: 'less common',
    type: 'nucleolarSpeckled',
    images: ["/images/patterns/ac-10/1473303336-0.jpg", "/images/patterns/ac-10/1473303368-0.jpg", "/images/patterns/ac-10/1473309686-0.jpg", "/images/patterns/ac-10/1473309724-0.jpg", "/images/patterns/ac-10/1473346664-0.jpg"],
  },
  {
    id: 'AC-11',
    name: 'Smooth Nuclear Envelope',
    category: 'nuclear',
    level: 'expert',
    tier: 3,
    description: 'Smooth continuous staining along nuclear membrane.',
    keyFeature: 'Bright rim/outline around entire nuclear perimeter, dark interior',
    antigens: 'Lamins A/B/C, lamin B receptor',
    clinicalAssociation: 'SLE, seronegative RA, linear scleroderma',
    confusedWith: ['AC-1', 'AC-12'],
    goblinNote: 'The nuclear castle wall glows smoothly. Different from the uniform interior glow of AC-1 — here it\'s just the envelope.',
    frequency: 'rare',
    type: 'nuclearEnvelope',
    images: ["/images/patterns/ac-11/1473303426-0.jpg", "/images/patterns/ac-11/1473308767-0.jpeg", "/images/patterns/ac-11/1473308781-0.jpg", "/images/patterns/ac-11/1473346678-0.jpg", "/images/patterns/ac-11/1617152242-0.jpg"],
  },
  {
    id: 'AC-12',
    name: 'Punctate Nuclear Envelope',
    category: 'nuclear',
    level: 'expert',
    tier: 3,
    description: 'Punctate/dotted staining along nuclear membrane.',
    keyFeature: 'Dots distributed along the nuclear membrane, not continuous',
    antigens: 'Nuclear pore complex proteins (gp210, Nup62)',
    clinicalAssociation: 'Primary biliary cholangitis (gp210 is highly specific)',
    confusedWith: ['AC-11', 'AC-6'],
    goblinNote: 'Same castle wall, but the antibodies hit specific gateposts instead of the whole wall. gp210 = PBC calling card.',
    frequency: 'rare',
    type: 'punctateEnvelope',
    images: ["/images/patterns/ac-12/1473303631-0.jpg", "/images/patterns/ac-12/1473303632-1.jpg", "/images/patterns/ac-12/1473303645-0.jpg", "/images/patterns/ac-12/1473303645-1.jpg", "/images/patterns/ac-12/1473308536-0.jpg"],
  },
  {
    id: 'AC-13',
    name: 'PCNA-like',
    category: 'nuclear',
    level: 'expert',
    tier: 3,
    description: 'Variable staining depending on cell cycle: mix of negative, dim, and bright nuclei in same field.',
    keyFeature: 'Pleomorphic — nuclei show varying intensities in the same field',
    antigens: 'PCNA (proliferating cell nuclear antigen)',
    clinicalAssociation: 'SLE (rare but specific)',
    confusedWith: ['AC-4', 'AC-2'],
    goblinNote: 'The pattern changes depending on where each cell is in its cycle — some nuclei glow bright (S-phase), some are dim, some dark. That pleomorphism IS the tell.',
    frequency: 'rare',
    type: 'pcnaLike',
    images: ["/images/patterns/ac-13/1473303722-0.jpg", "/images/patterns/ac-13/1473303809-0.jpg", "/images/patterns/ac-13/1473346781-0.jpg", "/images/patterns/ac-13/1520509442-0.jpg", "/images/patterns/ac-13/1520600573-0.jpg"],
  },
  {
    id: 'AC-14',
    name: 'CENP-F-like',
    category: 'nuclear',
    level: 'expert',
    tier: 3,
    description: 'Weak/negative interphase nuclei BUT bright metaphase chromatin. The "ninja pattern."',
    keyFeature: 'Mostly dark interphase nuclei, but dividing cells light up brightly at metaphase plate',
    antigens: 'CENP-F (mitosin)',
    clinicalAssociation: 'Various cancers, some autoimmune conditions',
    confusedWith: ['AC-3', 'AC-28'],
    goblinNote: 'The ninja pattern — hides during interphase, reveals itself during mitosis. Almost the opposite of what you\'d expect.',
    frequency: 'rare',
    type: 'cenpF',
    images: ["/images/patterns/ac-14/1473303877-0.jpg", "/images/patterns/ac-14/1473303877-1.jpg", "/images/patterns/ac-14/1473303922-0.jpg", "/images/patterns/ac-14/1473303922-1.jpg", "/images/patterns/ac-14/1473346790-0.jpg"],
  },
  {
    id: 'AC-15',
    name: 'Cytoplasmic Fibrillar Linear',
    category: 'cytoplasmic',
    level: 'competent',
    tier: 2,
    description: 'Linear fibers following actin stress fibers.',
    keyFeature: 'Linear fiber pattern following cellular axes',
    antigens: 'F-actin (smooth muscle antibodies/SMA), non-muscle myosin',
    clinicalAssociation: 'Autoimmune hepatitis type 1, chronic active hepatitis',
    confusedWith: ['AC-16', 'AC-17'],
    goblinNote: 'The cytoskeleton\'s cables lit up like highway lines. Anti-smooth muscle antibodies = think liver.',
    frequency: 'uncommon',
    type: 'cytoplasmicLinear',
    images: ["/images/patterns/ac-15/1473304507-0.jpg", "/images/patterns/ac-15/1473304532-0.jpg", "/images/patterns/ac-15/1473346808-0.jpg", "/images/patterns/ac-15/1617152307-0.jpg"],
  },
  {
    id: 'AC-16',
    name: 'Cytoplasmic Fibrillar Filamentous',
    category: 'cytoplasmic',
    level: 'competent',
    tier: 2,
    description: 'Network pattern following intermediate filaments.',
    keyFeature: 'Network/meshwork pattern in cytoplasm',
    antigens: 'Vimentin, cytokeratin',
    clinicalAssociation: 'Various infections, autoimmune conditions, often clinically insignificant',
    confusedWith: ['AC-15', 'AC-17'],
    goblinNote: 'The cell\'s internal scaffolding is glowing — a different kind of cable than AC-15\'s actin fibers.',
    frequency: 'uncommon',
    type: 'cytoplasmicNetwork',
    images: ["/images/patterns/ac-16/1473304601-0.jpg", "/images/patterns/ac-16/1473304655-1.jpg", "/images/patterns/ac-16/1473346828-0.jpg", "/images/patterns/ac-16/1617152380-0.jpg", "/images/patterns/ac-16/1626570418-0.jpg"],
  },
  {
    id: 'AC-17',
    name: 'Cytoplasmic Fibrillar Segmental',
    category: 'cytoplasmic',
    level: 'competent',
    tier: 2,
    description: 'Discontinuous/segmental fiber staining.',
    keyFeature: 'Dashed or segmental lines in cytoplasm',
    antigens: 'Alpha-actinin, vinculin',
    clinicalAssociation: 'Very rare in diagnostic serology',
    confusedWith: ['AC-15', 'AC-16'],
    goblinNote: 'The dashed lines of the cytoskeleton. One of the rarest patterns to actually encounter in clinical practice.',
    frequency: 'very rare',
    type: 'cytoplasmicSegmental',
    images: ["/images/patterns/ac-17/1473304741-0.jpg", "/images/patterns/ac-17/1473304743-1.jpg", "/images/patterns/ac-17/1520600731-0.jpg"],
  },
  {
    id: 'AC-18',
    name: 'Cytoplasmic Discrete Dots / GW Bodies',
    category: 'cytoplasmic',
    level: 'competent',
    tier: 2,
    description: 'Few large bright dots in cytoplasm (4-20 per cell). GW body/P-body components.',
    keyFeature: 'Few large bright dots in cytoplasm (not nucleus)',
    antigens: 'GW182, Ge-1 (GW body/P-body components, mRNA processing)',
    clinicalAssociation: 'Various autoimmune, neurological conditions',
    confusedWith: ['AC-7', 'AC-20'],
    goblinNote: 'The cell\'s mRNA shredding stations light up. GW bodies are where the cell processes and degrades messenger RNA.',
    frequency: 'uncommon',
    type: 'cytoplasmicGWDots',
    images: ["/images/patterns/ac-18/1473305013-0.jpg", "/images/patterns/ac-18/1473305033-0.jpg", "/images/patterns/ac-18/1505098141-0.jpg", "/images/patterns/ac-18/1617152436-0.jpg", "/images/patterns/ac-18/1625700204-0.jpg"],
  },
  {
    id: 'AC-19',
    name: 'Cytoplasmic Dense Fine Speckled',
    category: 'cytoplasmic',
    level: 'competent',
    tier: 2,
    description: 'Dense homogeneous/fine speckled cytoplasmic staining.',
    keyFeature: 'Dense uniform or fine speckled staining throughout cytoplasm',
    antigens: 'PL-7, PL-12, ribosomal P protein, SRP (signal recognition particle), Jo-1/histidyl-tRNA synthetase',
    clinicalAssociation: 'Anti-synthetase syndrome, SLE (anti-ribosomal P), polymyositis',
    confusedWith: ['AC-20', 'AC-21'],
    goblinNote: 'When the cytoplasm glows uniformly — anti-ribosomal P (SLE with neuropsychiatric features) or anti-Jo-1 (the mechanic\'s hands antibody in anti-synthetase syndrome).',
    frequency: 'moderately common',
    type: 'cytoplasmicDenseSpeckled',
    images: ["/images/patterns/ac-19/1473305085-0.jpg", "/images/patterns/ac-19/1473305146-0.jpg", "/images/patterns/ac-19/1473305163-0.jpg", "/images/patterns/ac-19/1473346880-0.jpg", "/images/patterns/ac-19/1617152464-0.jpg"],
  },
  {
    id: 'AC-20',
    name: 'Cytoplasmic Fine Speckled',
    category: 'cytoplasmic',
    level: 'competent',
    tier: 1,
    description: 'Fine speckled pattern in cytoplasm, nucleus appears relatively clean.',
    keyFeature: 'Stars in the cytoplasm, dark nucleus',
    antigens: 'Jo-1/anti-synthetases, anti-SRP, PL-7, PL-12',
    clinicalAssociation: 'Polymyositis, dermatomyositis, anti-synthetase syndrome',
    confusedWith: ['AC-19', 'AC-21'],
    goblinNote: 'Stars in the cytoplasm, dark nucleus. This is one of the most commonly detected cytoplasmic patterns.',
    frequency: 'very common',
    type: 'cytoplasmicSpeckled',
    images: ["/images/patterns/ac-20/1473305217-0.jpg", "/images/patterns/ac-20/1473305217-1.jpg", "/images/patterns/ac-20/1473305237-0.jpg", "/images/patterns/ac-20/1473305237-1.jpg", "/images/patterns/ac-20/1473346896-0.jpg"],
  },
  {
    id: 'AC-21',
    name: 'Cytoplasmic Reticular/AMA (Mitochondrial-like)',
    category: 'cytoplasmic',
    level: 'competent',
    tier: 2,
    description: 'Dense reticular/granular cytoplasmic staining following mitochondrial distribution.',
    keyFeature: 'Net-like/reticular pattern throughout cytoplasm',
    antigens: 'AMA (anti-mitochondrial antibodies, targeting PDC-E2)',
    clinicalAssociation: 'Primary biliary cholangitis (>95% specific for PBC)',
    confusedWith: ['AC-19', 'AC-20'],
    goblinNote: 'The janitors (complement) love this one — AMA targeting the mitochondria is practically a PBC diagnosis on a slide. The reticular pattern is the powerhouses crying for help.',
    frequency: 'common in PBC',
    type: 'cytoplasmicReticular',
    images: ["/images/patterns/ac-21/1473305288-0.jpg", "/images/patterns/ac-21/1473305347-0.jpg", "/images/patterns/ac-21/1473346907-0.jpg", "/images/patterns/ac-21/1617152533-0.jpg", "/images/patterns/ac-21/processed_QFxq5gOnZvJxUR43LCUAomzRZegrj03Vvct768Q0.jpg"],
  },
  {
    id: 'AC-22',
    name: 'Polar/Golgi-like',
    category: 'cytoplasmic',
    level: 'competent',
    tier: 2,
    description: 'Polar juxtanuclear crescent/cap shape.',
    keyFeature: 'Bright crescent or cap on one side of the nucleus',
    antigens: 'Golgin-95, golgin-97, giantin (Golgi matrix proteins)',
    clinicalAssociation: 'SLE, Sj\u00F6gren\'s, cerebellar ataxia, viral infections',
    confusedWith: ['AC-19', 'AC-20'],
    goblinNote: 'The cell\'s post office — packaging and shipping proteins. A bright crescent hugging the nucleus.',
    frequency: 'uncommon',
    type: 'cytoplasmicGolgi',
    images: ["/images/patterns/ac-22/1473305428-0.jpg", "/images/patterns/ac-22/1473305449-0.jpg", "/images/patterns/ac-22/1473307796-1.jpg", "/images/patterns/ac-22/1564361861-0.jpg", "/images/patterns/ac-22/1617152565-0.jpg"],
  },
  {
    id: 'AC-23',
    name: 'Rods and Rings',
    category: 'cytoplasmic',
    level: 'expert',
    tier: 3,
    description: 'Distinct rod-shaped and ring-shaped cytoplasmic inclusions.',
    keyFeature: 'Literal rods and rings as distinct shapes in cytoplasm',
    antigens: 'IMPDH2, CTPS1',
    clinicalAssociation: 'Strongly associated with HCV treatment (interferon/ribavirin)',
    confusedWith: ['AC-18', 'AC-20'],
    goblinNote: 'The weirdest pattern in the catalog — literal rods and rings floating in the cytoplasm. Originally discovered in HCV patients on treatment. The shape is unmistakable once you\'ve seen it.',
    frequency: 'rare',
    type: 'rodsAndRings',
    images: ["/images/patterns/ac-23/1473306070-0.jpg", "/images/patterns/ac-23/1473306086-0.jpg", "/images/patterns/ac-23/1473307298-0.jpg", "/images/patterns/ac-23/1473307298-1.jpg", "/images/patterns/ac-23/1473346971-0.jpg"],
  },
  // MITOTIC PATTERNS
  {
    id: 'AC-24',
    name: 'Centrosome',
    category: 'mitotic',
    level: 'expert',
    tier: 4,
    description: 'Bright dots at spindle poles during mitosis (1-2 dots at each pole). Also visible as perinuclear dots in interphase.',
    keyFeature: '1-2 bright dots at each spindle pole in dividing cells',
    antigens: 'Pericentrin, ninein, Cep250, enolase',
    clinicalAssociation: 'Systemic sclerosis, Raynaud\'s, Sj\u00F6gren\'s',
    confusedWith: ['AC-18', 'AC-25'],
    goblinNote: 'The cell\'s division HQ lights up — bright beacons at the poles where the spindle assembles.',
    frequency: 'uncommon',
    type: 'centrosome',
    images: ["/images/patterns/ac-24/1473306237-0.jpg", "/images/patterns/ac-24/1473306263-0.jpg", "/images/patterns/ac-24/1473346982-0.jpg", "/images/patterns/ac-24/1520600896-0.jpg", "/images/patterns/ac-24/1617152601-0.jpg"],
  },
  {
    id: 'AC-25',
    name: 'Mitotic Spindle Apparatus (MSA)',
    category: 'mitotic',
    level: 'expert',
    tier: 4,
    description: 'Staining along spindle fibers connecting the poles during mitosis. THE KEY PATTERN AI FAILS AT.',
    keyFeature: 'Lines/fibers connecting spindle poles during mitosis',
    antigens: 'HsEg5/KSP, MSA-related proteins',
    clinicalAssociation: 'Various, not strongly disease-associated alone',
    confusedWith: ['AC-24', 'AC-26'],
    goblinNote: 'THE pattern that makes AI systems see "mitosis but green" and give up. Your human pattern recognition is better than Quest\'s algorithm here. The spindle fibers between the poles are the tell — not just the poles themselves.',
    frequency: 'uncommon',
    type: 'spindleApparatus',
    images: ["/images/patterns/ac-25/1473306309-0.jpg", "/images/patterns/ac-25/1473306310-1.jpg", "/images/patterns/ac-25/1473308441-0.jpg", "/images/patterns/ac-25/1505098226-0.jpg", "/images/patterns/ac-25/1617152656-0.jpg"],
  },
  {
    id: 'AC-26',
    name: 'NuMA-like',
    category: 'mitotic',
    level: 'expert',
    tier: 4,
    description: 'Staining of spindle poles and proximal spindle fibers with characteristic NuMA distribution. Bright at poles, fans out.',
    keyFeature: 'Fan-shaped glow at spindle poles, wider than centrosome dots',
    antigens: 'NuMA-1 (nuclear mitotic apparatus protein)',
    clinicalAssociation: 'Sj\u00F6gren\'s, SLE, MCTD',
    confusedWith: ['AC-25', 'AC-24'],
    goblinNote: 'Like AC-25\'s cousin — NuMA protein creates a fan-shaped glow at the poles. The shape is the clue.',
    frequency: 'very rare',
    type: 'numaLike',
    images: ["/images/patterns/ac-26/1473306362-0.jpg", "/images/patterns/ac-26/1473306379-0.jpg", "/images/patterns/ac-26/1505098250-0.jpg", "/images/patterns/ac-26/1617152715-0.jpg", "/images/patterns/ac-26/1625700320-0.jpg"],
  },
  {
    id: 'AC-27',
    name: 'Intercellular Bridge / Stem Body',
    category: 'mitotic',
    level: 'expert',
    tier: 4,
    description: 'Bright staining at the intercellular bridge (midbody) between cells in late telophase.',
    keyFeature: 'Bright dot at the pinch point between two dividing cells',
    antigens: 'Various midbody proteins',
    clinicalAssociation: 'Various autoimmune',
    confusedWith: ['AC-25', 'AC-28'],
    goblinNote: 'The bridge between two dividing cells lights up — a single bright dot right at the pinch point where one cell becomes two.',
    frequency: 'rare (most common rare pattern at 0.78%)',
    type: 'intercellularBridge',
    images: ["/images/patterns/ac-27/1473306403-0.jpg", "/images/patterns/ac-27/1473306447-0.jpg", "/images/patterns/ac-27/1473306448-1.jpg", "/images/patterns/ac-27/1473309430-0.jpg", "/images/patterns/ac-27/1505098287-0.jpg"],
  },
  {
    id: 'AC-28',
    name: 'Mitotic Chromosomal Coat',
    category: 'mitotic',
    level: 'expert',
    tier: 4,
    description: 'Diffuse staining coating the condensed chromosomes during mitosis.',
    keyFeature: 'Bright staining on condensed chromosome mass during mitosis',
    antigens: 'Modified/phosphorylated histones, MCA (mitotic chromosome autoantibodies)',
    clinicalAssociation: 'Discoid lupus, various',
    confusedWith: ['AC-1', 'AC-25', 'AC-27'],
    goblinNote: 'The entire chromosome book is glowing — not just the spine (centromere) but the whole thing, coated in antibodies. Distinguished from AC-1 because the staining is ONLY on mitotic chromosomes.',
    frequency: 'uncommon',
    type: 'chromosomalCoat',
    images: ["/images/patterns/ac-28/1473306489-0.jpg", "/images/patterns/ac-28/1473306489-1.jpg", "/images/patterns/ac-28/1487962871-0.jpg"],
  },
  // COMPOSITE PATTERNS
  {
    id: 'AC-29',
    name: 'Topoisomerase I-like (Scl-70)',
    category: 'nuclear',
    level: 'expert',
    tier: 3,
    description: 'COMPOSITE pattern with 5 simultaneous elements: nuclear fine speckled + nucleolar staining + metaphase plate + perichromosomal staining + cytoplasmic haze.',
    keyFeature: 'Multiple pattern elements visible simultaneously (composite)',
    antigens: 'DNA topoisomerase I (Scl-70)',
    clinicalAssociation: 'Diffuse cutaneous systemic sclerosis (highly specific)',
    confusedWith: ['AC-4', 'AC-8'],
    goblinNote: 'The five-headed dragon of patterns — Gryf\'s anti-Scl-70 antibodies create a signature so complex it\'s essentially a fingerprint for diffuse scleroderma. Five elements at once. If you can spot all five, you\'re better than most lab techs.',
    frequency: 'rare but clinically critical',
    type: 'topoIsomerase',
    images: ["/images/patterns/ac-29/1502477796-0.jpg", "/images/patterns/ac-29/1502478269-0.jpg", "/images/patterns/ac-29/1520600972-0.jpg", "/images/patterns/ac-29/1625700370-0.jpg", "/images/patterns/ac-29/1625700423-0.jpg"],
  },
  {
    id: 'AC-30',
    name: 'Nuclear Fine Speckled with Mitotic Plate',
    category: 'nuclear',
    level: 'expert',
    tier: 3,
    description: 'Fine speckled but MORE UNIFORM than AC-2\'s heterogeneous lunar surface. OPPOSITE of AC-2 — indicates systemic autoimmune disease.',
    keyFeature: 'More uniform speckles than AC-2, less heterogeneous',
    antigens: 'NOT DFS70 — disease-causing antibodies (nucleosomes, dsDNA, Ro/La, RNP/Sm, Scl-70)',
    clinicalAssociation: 'Indicates systemic autoimmune disease (OPPOSITE of AC-2)',
    confusedWith: ['AC-2', 'AC-4'],
    goblinNote: 'AC-2\'s evil twin. Looks similar but means the opposite. AC-2 (DFS70) = probably fine. AC-30 = the goblins are actually here. The difference is speckle uniformity. This is one of the most important distinctions in the whole system.',
    frequency: 'emerging',
    type: 'uniformSpeckled',
    images: ["/images/patterns/ac-30/3KOxoQNKNj9AL5Hw3oo5YOvRq0iofqpe3v6LVwGO.jpg", "/images/patterns/ac-30/JCzxv0Pg042MhQpDGFhNXp0uvhApv0bvBXspOQHM.jpg", "/images/patterns/ac-30/RES3g0UaxvrUi3ARNDT4rjsD9PYNPVYfluP0gD7e.jpg", "/images/patterns/ac-30/iV76C6R7urrVKAGIBmuwpB7LjjZgZZR6MhjKzO6c.jpg", "/images/patterns/ac-30/tCadI5hORB7JRfGFI04gKUtE5PeOQIv0coqEcQBQ.jpg"],
  },
  {
    id: 'AC-31',
    name: 'Myriad Discrete Fine Speckled',
    category: 'nuclear',
    level: 'expert',
    tier: 4,
    description: 'Innumerable tiny discrete dots throughout nucleus, denser and more discrete than AC-4.',
    keyFeature: 'Sea of tiny discrete dots, much denser than AC-4',
    antigens: 'Anti-Ro60/SS-A (strongly associated)',
    clinicalAssociation: 'Sj\u00F6gren\'s, neonatal lupus, subacute cutaneous lupus',
    confusedWith: ['AC-4', 'AC-2'],
    goblinNote: 'Gryf again (IgG anti-Ro60 crosses the placenta) — a sea of tiny stars. Anti-Ro60 is one of the antibodies that can affect a baby before it\'s born. The myriad dots are its calling card.',
    frequency: 'emerging',
    type: 'myriads',
    images: ["/images/patterns/ac-31/TfLDMuDPckI26UEmXIJWDB4iEhWG7shedWh429KV.jpg", "/images/patterns/ac-31/VqVXrxjVvJYDtPbsg0md132i96C0YNcR5hvV1UP5.jpg", "/images/patterns/ac-31/ZSOnGFCOyR4uX90se83o1HBvdD9W3poohjMZ0PgL.jpg", "/images/patterns/ac-31/bkoXTPuzOCaMowRJn6Bwtm5628TCiTiXW7nyrHpz.jpg", "/images/patterns/ac-31/gDH8O6zYbJhSXaaqzq467uDjMg71IsDaMYZgTgCE.jpg"],
  },
];

export default PATTERNS;
